language: ruby
cache:
  bundler: true
  directories:
    - $HOME/.m2
before_script:
  - export JRUBY_VERSION=$(ruby --version | perl -n -e '/jruby (\S+)/ && print $1')
script: '(cd ext && mvn test -Djruby.version=$JRUBY_VERSION) && bundle exec rake'
rvm:
  - jruby-19mode
  - jruby-9.1.2.0
